# [START runtime]
runtime: python27
threadsafe: yes
# [END runtime]

handlers:
  - url: /(.*\.(js|map|css|png|ico|json))$
    static_files: \1
    upload: .*\.(js|map|css|png|ico|json)$

  - url: .*
    static_files: index.min.html
    upload: index.min.html
    secure: always

# Temporary setting to keep gcloud from uploading not required files for deployment
skip_files:
- ^node_modules$
- ^app\.yaml
- ^README\..*
- \.gitignore
- ^\.git$
- ^grunt\.js
- ^src$
- ^e2e$
- \.editorconfig
- ^karma\.config\.js
- ^package\.json
- ^protractor\.conf\.js
- ^tslint\.json